version: '3'

services:

  abes-filebeat:
    image: docker.elastic.co/beats/filebeat:7.17.9
    container_name: abes-filebeat
    restart: unless-stopped
    mem_limit: ${MEM_LIMIT}
    user: root
    volumes:
      - ./filebeat.docker.yml:/usr/share/filebeat/filebeat.yml:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    environment:
#      - ELASTICSEARCH_HOST=${ELASTICSEARCH_HOST:-node1}
#      - KIBANA_HOST=${KIBANA_HOST:-node1}
#      - ELASTICSEARCH_USERNAME=${ELASTICSEARCH_USERNAME:-elastic}
#      - ELASTICSEARCH_PASSWORD=${ELASTICSEARCH_PASSWORD:-changeme}
      - LOGSTASH_HOST=${LOGSTASH_HOST:-logstashhost}
    command: ["-e", "--strict.perms=false"]



  abes-filebeat-app-exemple:
    image: nginx:latest
    container_name: abes-filebeat-app-exemple
    restart: unless-stopped
    mem_limit: ${MEM_LIMIT}
    ports:
      - 8081:80
    labels:
      - "co.elastic.logs/enabled=true"
      - "co.elastic.logs/module=nginx"
      - "co.elastic.logs/fileset.stdout=access"
      - "co.elastic.logs/fileset.stderr=error"
      - "co.elastic.logs/processors.add_fields.target="
      - "co.elastic.logs/processors.add_fields.fields.abes_appli=abes-filebeat-app-exemple"
      - "co.elastic.logs/processors.add_fields.fields.abes_middleware=Httpd"
    profiles: ["debug"]

