# Filebeat configuration

filebeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true
      hints.default_config:
        type: container
        paths:
          - /var/lib/docker/containers/${data.container.id}/*.log

filebeat.config:
  modules:
    # In Ubuntu container:   path: /usr/share/filebeat/modules.d/
    path: ${path.config}/modules.d/*.yml
    reload.enabled: true

processors:
# If running in a cloud environment: - add_cloud_metadata: ~
- drop_fields:
    when:
      contains:
        message: "_nuxt"
    fields: ["message", "event.original"]
    ignore_missing: true

- drop_fields:
    when:
      contains:
        abes_appli: "qualinka-ms"
    fields: ["container.labels", "docker.container.labels.io_buildpacks_build_metadata", "docker.container.labels.io_buildpacks_lifecycle_metadata", "docker.container.labels.io_buildpacks_stack_mixins", "docker.container.labels.io_paketo_stack_packages", "docker.container.labels.io_buildpacks_project_metadata", "docker.container.labels.io_buildpacks_stack_description", "docker.container.labels.io_buildpacks_stack_homepage", "docker.container.labels.io_buildpacks_stack_id", " docker.container.labels.io_buildpacks_stack_maintainer", "docker.container.labels.io_buildpacks_stack_maintainer", "docker.container.labels.io_buildpacks_stack_metadata", "docker.container.labels.io_buildpacks_stack_released"]
    ignore_missing: true

output.logstash: 
  enabled: true 
 
  # The Logstash hosts 
  hosts: '${LOGSTASH_HOST}'

